server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route
          #uri: http://localhost:8001
          uri: lb://cloud-test-service
          predicates:
            - Path=/payment/get/**

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-test-service
          predicates:
            - Path=/payment/lb/**
            - After=2022-01-10T18:42:16.745+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka